

version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-jornal
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: jornalBD
    ports:
      - "3307:3306"
    volumes:
      - jornal-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  jornal-mysql-data:





