-- Tabela Tema
CREATE TABLE IF NOT EXISTS tema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    caminho_imagem VARCHAR(255) NOT NULL
);

-- Tabela Rodape
CREATE TABLE IF NOT EXISTS rodape (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_loja BIGINT NOT NULL UNIQUE,
    caminho_imagem VARCHAR(255) NOT NULL
);

-- Tabela Produto
CREATE TABLE IF NOT EXISTS produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ean BIGINT NOT NULL UNIQUE,
    descricao VARCHAR(255) NOT NULL,
    preco_de DECIMAL(10,2),
    preco_por DECIMAL(10,2) NOT NULL,
    classificacao VARCHAR(20) CHECK (classificacao IN ('MEDICAMENTO','PERFUMARIA')),
    caminho_imagem VARCHAR(255),
    isento BOOLEAN NOT NULL DEFAULT FALSE
);

-- Tabela Projeto
CREATE TABLE IF NOT EXISTS projeto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    tema_id BIGINT NOT NULL,
    rodape_id BIGINT NOT NULL,
    CONSTRAINT fk_projeto_tema FOREIGN KEY (tema_id) REFERENCES tema(id),
    CONSTRAINT fk_projeto_rodape FOREIGN KEY (rodape_id) REFERENCES rodape(id)
);

-- Tabela de relacionamento Projeto_Produto
CREATE TABLE IF NOT EXISTS projeto_produto (
    projeto_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    PRIMARY KEY (projeto_id, produto_id),
    CONSTRAINT fk_pp_projeto FOREIGN KEY (projeto_id) REFERENCES projeto(id),
    CONSTRAINT fk_pp_produto FOREIGN KEY (produto_id) REFERENCES produto(id)
);
