-- Tabela de relatório de uso
CREATE TABLE relatorio_uso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_cliente VARCHAR(4) NOT NULL,
    data_uso TIMESTAMP NOT NULL,
    projeto_id BIGINT,
    tipo_geracao VARCHAR(20),
    quantidade_produtos INT,
    nome_tema VARCHAR(255),
    periodo_validade VARCHAR(100),
    CONSTRAINT fk_relatorio_uso_projeto FOREIGN KEY (projeto_id) REFERENCES projeto(id) ON DELETE SET NULL
);

CREATE INDEX idx_relatorio_uso_codigo_cliente ON relatorio_uso (codigo_cliente);
CREATE INDEX idx_relatorio_uso_data_uso ON relatorio_uso (data_uso);

-- Tabela de clientes para relatórios
CREATE TABLE relatorio_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_cliente VARCHAR(4) NOT NULL UNIQUE,
    nome_cliente VARCHAR(255),
    data_registro DATE,
    total_uso INT DEFAULT 0,
    ultimo_uso TIMESTAMP,
    ativo BOOLEAN DEFAULT TRUE
);

CREATE INDEX idx_relatorio_cliente_codigo_cliente ON relatorio_cliente (codigo_cliente);
CREATE INDEX idx_relatorio_cliente_ativo ON relatorio_cliente (ativo);

-- Inserir clientes base a partir dos rodapés existentes
INSERT INTO relatorio_cliente (codigo_cliente, nome_cliente, data_registro, ativo)
SELECT DISTINCT
    CAST(codigo_loja AS VARCHAR) AS codigo_cliente,
    CONCAT('Cliente ', CAST(codigo_loja AS VARCHAR)) AS nome_cliente,
    CURRENT_DATE AS data_registro,
    TRUE AS ativo
FROM rodape;
